# Generated by Django 5.1.4 on 2025-01-17 09:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_alter_follow_id_alter_post_id_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='userLike',
            field=models.ManyToManyField(blank=True, related_name='liked_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
